# Generated by Django 4.0.4 on 2022-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpredict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RidgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('mae', models.FloatField(default=0)),
                ('mse', models.FloatField(default=0)),
                ('file_model', models.FileField(default=None, upload_to='')),
            ],
            options={
                'verbose_name': 'Модель линейной регресии',
                'verbose_name_plural': 'Модели линейной регресии',
                'db_table': 'ridge',
                'ordering': ['id'],
            },
        ),
    ]
